//
// Generated by Bluespec Compiler, version 2024.01-9-gc481d7f5 (build c481d7f5)
//
// On Tue Nov 26 19:41:09 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // register as1
  reg [7 : 0] as1;
  wire [7 : 0] as1$D_IN;
  wire as1$EN;

  // register as2
  reg [7 : 0] as2;
  wire [7 : 0] as2$D_IN;
  wire as2$EN;

  // register as3
  reg [7 : 0] as3;
  wire [7 : 0] as3$D_IN;
  wire as3$EN;

  // register as4
  reg [7 : 0] as4;
  wire [7 : 0] as4$D_IN;
  wire as4$EN;

  // register as5
  reg [7 : 0] as5;
  wire [7 : 0] as5$D_IN;
  wire as5$EN;

  // register as6
  reg [7 : 0] as6;
  wire [7 : 0] as6$D_IN;
  wire as6$EN;

  // register bs1
  reg [7 : 0] bs1;
  wire [7 : 0] bs1$D_IN;
  wire bs1$EN;

  // register bs2
  reg [7 : 0] bs2;
  wire [7 : 0] bs2$D_IN;
  wire bs2$EN;

  // register bs3
  reg [7 : 0] bs3;
  wire [7 : 0] bs3$D_IN;
  wire bs3$EN;

  // register bs4
  reg [7 : 0] bs4;
  wire [7 : 0] bs4$D_IN;
  wire bs4$EN;

  // register bs5
  reg [7 : 0] bs5;
  wire [7 : 0] bs5$D_IN;
  wire bs5$EN;

  // register bs6
  reg [7 : 0] bs6;
  wire [7 : 0] bs6$D_IN;
  wire bs6$EN;

  // register crg_bc
  reg [31 : 0] crg_bc;
  wire [31 : 0] crg_bc$D_IN;
  wire crg_bc$EN;

  // register cs1
  reg [31 : 0] cs1;
  wire [31 : 0] cs1$D_IN;
  wire cs1$EN;

  // register cs2
  reg [31 : 0] cs2;
  wire [31 : 0] cs2$D_IN;
  wire cs2$EN;

  // register cs3
  reg [31 : 0] cs3;
  wire [31 : 0] cs3$D_IN;
  wire cs3$EN;

  // register cs4
  reg [31 : 0] cs4;
  wire [31 : 0] cs4$D_IN;
  wire cs4$EN;

  // register cs5
  reg [31 : 0] cs5;
  wire [31 : 0] cs5$D_IN;
  wire cs5$EN;

  // register cs6
  reg [31 : 0] cs6;
  wire [31 : 0] cs6$D_IN;
  wire cs6$EN;

  // register fail
  reg [10 : 0] fail;
  wire [10 : 0] fail$D_IN;
  wire fail$EN;

  // register obj_mac_rg_a
  reg [7 : 0] obj_mac_rg_a;
  wire [7 : 0] obj_mac_rg_a$D_IN;
  wire obj_mac_rg_a$EN;

  // register obj_mac_rg_b
  reg [7 : 0] obj_mac_rg_b;
  wire [7 : 0] obj_mac_rg_b$D_IN;
  wire obj_mac_rg_b$EN;

  // register obj_mac_rg_stage1_op_0
  reg [15 : 0] obj_mac_rg_stage1_op_0;
  wire [15 : 0] obj_mac_rg_stage1_op_0$D_IN;
  wire obj_mac_rg_stage1_op_0$EN;

  // register obj_mac_rg_stage1_op_1
  reg [15 : 0] obj_mac_rg_stage1_op_1;
  wire [15 : 0] obj_mac_rg_stage1_op_1$D_IN;
  wire obj_mac_rg_stage1_op_1$EN;

  // register obj_mac_rg_stage1_op_2
  reg [15 : 0] obj_mac_rg_stage1_op_2;
  wire [15 : 0] obj_mac_rg_stage1_op_2$D_IN;
  wire obj_mac_rg_stage1_op_2$EN;

  // register obj_mac_rg_stage1_op_3
  reg [15 : 0] obj_mac_rg_stage1_op_3;
  wire [15 : 0] obj_mac_rg_stage1_op_3$D_IN;
  wire obj_mac_rg_stage1_op_3$EN;

  // register obj_mac_rg_stage1_op_4
  reg [15 : 0] obj_mac_rg_stage1_op_4;
  wire [15 : 0] obj_mac_rg_stage1_op_4$D_IN;
  wire obj_mac_rg_stage1_op_4$EN;

  // register obj_mac_rg_stage2_op_0
  reg [15 : 0] obj_mac_rg_stage2_op_0;
  wire [15 : 0] obj_mac_rg_stage2_op_0$D_IN;
  wire obj_mac_rg_stage2_op_0$EN;

  // register obj_mac_rg_stage2_op_1
  reg [15 : 0] obj_mac_rg_stage2_op_1;
  wire [15 : 0] obj_mac_rg_stage2_op_1$D_IN;
  wire obj_mac_rg_stage2_op_1$EN;

  // register obj_mac_rg_stage2_op_2
  reg [15 : 0] obj_mac_rg_stage2_op_2;
  wire [15 : 0] obj_mac_rg_stage2_op_2$D_IN;
  wire obj_mac_rg_stage2_op_2$EN;

  // register obj_mac_rg_stage3_op_0
  reg [15 : 0] obj_mac_rg_stage3_op_0;
  wire [15 : 0] obj_mac_rg_stage3_op_0$D_IN;
  wire obj_mac_rg_stage3_op_0$EN;

  // register obj_mac_rg_stage3_op_1
  reg [15 : 0] obj_mac_rg_stage3_op_1;
  wire [15 : 0] obj_mac_rg_stage3_op_1$D_IN;
  wire obj_mac_rg_stage3_op_1$EN;

  // register obj_mac_rg_stage4_op
  reg [15 : 0] obj_mac_rg_stage4_op;
  wire [15 : 0] obj_mac_rg_stage4_op$D_IN;
  wire obj_mac_rg_stage4_op$EN;

  // register obj_mac_rg_stage5_op
  reg [31 : 0] obj_mac_rg_stage5_op;
  wire [31 : 0] obj_mac_rg_stage5_op$D_IN;
  wire obj_mac_rg_stage5_op$EN;

  // register obj_mac_s1_a
  reg [7 : 0] obj_mac_s1_a;
  wire [7 : 0] obj_mac_s1_a$D_IN;
  wire obj_mac_s1_a$EN;

  // register obj_mac_s1_b
  reg [7 : 0] obj_mac_s1_b;
  wire [7 : 0] obj_mac_s1_b$D_IN;
  wire obj_mac_s1_b$EN;

  // register obj_mac_s1_c
  reg [31 : 0] obj_mac_s1_c;
  wire [31 : 0] obj_mac_s1_c$D_IN;
  wire obj_mac_s1_c$EN;

  // register obj_mac_s2_a
  reg [7 : 0] obj_mac_s2_a;
  wire [7 : 0] obj_mac_s2_a$D_IN;
  wire obj_mac_s2_a$EN;

  // register obj_mac_s2_b
  reg [7 : 0] obj_mac_s2_b;
  wire [7 : 0] obj_mac_s2_b$D_IN;
  wire obj_mac_s2_b$EN;

  // register obj_mac_s2_c
  reg [31 : 0] obj_mac_s2_c;
  wire [31 : 0] obj_mac_s2_c$D_IN;
  wire obj_mac_s2_c$EN;

  // register obj_mac_s3_a
  reg [7 : 0] obj_mac_s3_a;
  wire [7 : 0] obj_mac_s3_a$D_IN;
  wire obj_mac_s3_a$EN;

  // register obj_mac_s3_b
  reg [7 : 0] obj_mac_s3_b;
  wire [7 : 0] obj_mac_s3_b$D_IN;
  wire obj_mac_s3_b$EN;

  // register obj_mac_s3_c
  reg [31 : 0] obj_mac_s3_c;
  wire [31 : 0] obj_mac_s3_c$D_IN;
  wire obj_mac_s3_c$EN;

  // register obj_mac_s4_a
  reg [7 : 0] obj_mac_s4_a;
  wire [7 : 0] obj_mac_s4_a$D_IN;
  wire obj_mac_s4_a$EN;

  // register obj_mac_s4_b
  reg [7 : 0] obj_mac_s4_b;
  wire [7 : 0] obj_mac_s4_b$D_IN;
  wire obj_mac_s4_b$EN;

  // register obj_mac_s4_c
  reg [31 : 0] obj_mac_s4_c;
  wire [31 : 0] obj_mac_s4_c$D_IN;
  wire obj_mac_s4_c$EN;

  // register obj_mac_s5_a
  reg [7 : 0] obj_mac_s5_a;
  wire [7 : 0] obj_mac_s5_a$D_IN;
  wire obj_mac_s5_a$EN;

  // register obj_mac_s5_b
  reg [7 : 0] obj_mac_s5_b;
  wire [7 : 0] obj_mac_s5_b$D_IN;
  wire obj_mac_s5_b$EN;

  // register obj_mac_s5_c
  reg [31 : 0] obj_mac_s5_c;
  wire [31 : 0] obj_mac_s5_c$D_IN;
  wire obj_mac_s5_c$EN;

  // register rg_A
  reg [7 : 0] rg_A;
  wire [7 : 0] rg_A$D_IN;
  wire rg_A$EN;

  // register rg_B
  reg [7 : 0] rg_B;
  wire [7 : 0] rg_B$D_IN;
  wire rg_B$EN;

  // register rg_C
  reg [31 : 0] rg_C;
  wire [31 : 0] rg_C$D_IN;
  wire rg_C$EN;

  // register rg_MAC
  reg [31 : 0] rg_MAC;
  wire [31 : 0] rg_MAC$D_IN;
  wire rg_MAC$EN;

  // register s1_MAC
  reg [31 : 0] s1_MAC;
  wire [31 : 0] s1_MAC$D_IN;
  wire s1_MAC$EN;

  // register s2_MAC
  reg [31 : 0] s2_MAC;
  wire [31 : 0] s2_MAC$D_IN;
  wire s2_MAC$EN;

  // register s3_MAC
  reg [31 : 0] s3_MAC;
  wire [31 : 0] s3_MAC$D_IN;
  wire s3_MAC$EN;

  // register s4_MAC
  reg [31 : 0] s4_MAC;
  wire [31 : 0] s4_MAC$D_IN;
  wire s4_MAC$EN;

  // register s5_MAC
  reg [31 : 0] s5_MAC;
  wire [31 : 0] s5_MAC$D_IN;
  wire s5_MAC$EN;

  // register s6_MAC
  reg [31 : 0] s6_MAC;
  wire [31 : 0] s6_MAC$D_IN;
  wire s6_MAC$EN;

  // ports of submodule inp
  wire [31 : 0] inp$mac, inp$outC;
  wire [10 : 0] inp$cnt;
  wire [7 : 0] inp$outA, inp$outB;
  wire inp$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_comp;

  // remaining internal signals
  wire [31 : 0] SEXT_obj_mac_rg_stage4_op_81___d682;
  wire [7 : 0] IF_x5132_OR_y5133_THEN_1_ELSE_0__q3,
	       _0_CONCAT_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_B_ETC___d75,
	       spliced_bits__h24729;
  wire [6 : 0] INV_x073__q1,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d132,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83,
	       x__h7073,
	       y__h7075;
  wire [5 : 0] obj_mac_rg_stage2_op_0_62_BIT_12_65_AND_obj_ma_ETC___d520,
	       spliced_bits__h11548,
	       spliced_bits__h13754;
  wire [3 : 0] IF_x8335_OR_y8336_THEN_1_ELSE_0__q2,
	       INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87,
	       obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328,
	       obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330,
	       obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417,
	       obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419,
	       obj_mac_rg_stage2_op_0_62_BIT_10_77_AND_obj_ma_ETC___d519,
	       obj_mac_rg_stage2_op_0_62_BIT_10_77_XOR_obj_ma_ETC___d496,
	       obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550,
	       obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552,
	       obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592,
	       obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594,
	       obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571,
	       obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573,
	       obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784,
	       obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763,
	       obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742,
	       obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721,
	       obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700,
	       obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685,
	       obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826,
	       obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828,
	       obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805,
	       p__h11717,
	       p__h13921,
	       p__h18741,
	       p__h34220,
	       p__h36048,
	       p__h37900,
	       p__h39751,
	       p__h41602,
	       p__h43453,
	       p__h45303,
	       p__h7515,
	       p__h9402,
	       rg_a__h10422,
	       rg_b__h13914,
	       spliced_bits__h11635,
	       spliced_bits__h13840,
	       spliced_bits__h16383,
	       spliced_bits__h18660,
	       spliced_bits__h20875,
	       spliced_bits__h2158,
	       spliced_bits__h2210,
	       spliced_bits__h26311,
	       spliced_bits__h26339,
	       spliced_bits__h26367,
	       spliced_bits__h26395,
	       spliced_bits__h33044,
	       spliced_bits__h33072,
	       spliced_bits__h33100,
	       spliced_bits__h33128,
	       spliced_bits__h33156,
	       spliced_bits__h33184,
	       spliced_bits__h33212,
	       spliced_bits__h33240,
	       spliced_bits__h7329,
	       spliced_bits__h7381,
	       spliced_bits__h7433,
	       y__h11721,
	       y__h13925,
	       y__h16474,
	       y__h18745,
	       y__h20961,
	       y__h2302,
	       y__h26478,
	       y__h27394,
	       y__h29256,
	       y__h33322,
	       y__h34224,
	       y__h36052,
	       y__h37904,
	       y__h39755,
	       y__h41606,
	       y__h43457,
	       y__h45307,
	       y__h7519,
	       y__h9406;
  wire [2 : 0] obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534,
	       obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d625,
	       obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536;
  wire [1 : 0] INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38,
	       INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42,
	       INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d73,
	       obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_AND_o_ETC___d377,
	       obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379,
	       obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389,
	       obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_XOR_o_ETC___d393;
  wire INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_4__ETC___d16,
       cin__h29245,
       cin__h31131,
       cin__h36041,
       cin__h37893,
       cin__h39744,
       cin__h41595,
       cin__h43446,
       cin__h45296,
       cin__h4622,
       obj_mac_rg_stage5_op_023_EQ_s6_MAC_024___d1025,
       x__h10995,
       x__h10997,
       x__h10999,
       x__h11069,
       x__h11136,
       x__h11226,
       x__h11852,
       x__h11854,
       x__h11925,
       x__h11992,
       x__h12097,
       x__h12167,
       x__h13204,
       x__h13206,
       x__h13208,
       x__h13278,
       x__h13345,
       x__h13435,
       x__h14087,
       x__h14158,
       x__h15413,
       x__h15415,
       x__h15485,
       x__h15552,
       x__h16609,
       x__h16611,
       x__h16682,
       x__h16749,
       x__h16856,
       x__h16926,
       x__h17967,
       x__h17969,
       x__h17971,
       x__h18041,
       x__h18108,
       x__h18198,
       x__h18939,
       x__h19009,
       x__h20255,
       x__h20257,
       x__h20324,
       x__h20388,
       x__h21094,
       x__h21096,
       x__h21167,
       x__h21234,
       x__h21340,
       x__h21410,
       x__h22451,
       x__h22453,
       x__h22455,
       x__h22525,
       x__h22592,
       x__h22682,
       x__h2464,
       x__h25202,
       x__h25204,
       x__h25399,
       x__h25401,
       x__h25596,
       x__h25598,
       x__h25793,
       x__h25795,
       x__h2598,
       x__h25990,
       x__h25992,
       x__h26615,
       x__h26686,
       x__h27527,
       x__h27529,
       x__h27600,
       x__h27667,
       x__h2770,
       x__h2772,
       x__h28335,
       x__h28337,
       x__h28407,
       x__h2843,
       x__h28474,
       x__h28690,
       x__h28760,
       x__h2910,
       x__h29389,
       x__h29391,
       x__h29462,
       x__h29529,
       x__h3015,
       x__h30216,
       x__h30218,
       x__h30220,
       x__h30290,
       x__h30357,
       x__h30447,
       x__h30576,
       x__h30646,
       x__h3121,
       x__h31278,
       x__h31280,
       x__h31349,
       x__h31413,
       x__h3191,
       x__h32097,
       x__h32099,
       x__h32101,
       x__h32171,
       x__h32238,
       x__h32328,
       x__h32457,
       x__h32524,
       x__h33446,
       x__h33517,
       x__h34341,
       x__h34343,
       x__h34414,
       x__h34481,
       x__h35132,
       x__h35134,
       x__h35204,
       x__h35271,
       x__h35487,
       x__h35557,
       x__h36169,
       x__h36171,
       x__h36242,
       x__h36309,
       x__h36979,
       x__h36981,
       x__h36983,
       x__h37053,
       x__h37120,
       x__h37210,
       x__h37339,
       x__h37409,
       x__h38021,
       x__h38023,
       x__h38094,
       x__h38161,
       x__h38830,
       x__h38832,
       x__h38834,
       x__h38904,
       x__h38971,
       x__h39061,
       x__h39190,
       x__h39260,
       x__h39872,
       x__h39874,
       x__h39945,
       x__h40012,
       x__h40681,
       x__h40683,
       x__h40685,
       x__h40755,
       x__h40822,
       x__h40912,
       x__h41041,
       x__h41111,
       x__h41723,
       x__h41725,
       x__h41796,
       x__h41863,
       x__h4228,
       x__h4230,
       x__h4232,
       x__h42532,
       x__h42534,
       x__h42536,
       x__h42606,
       x__h42673,
       x__h42763,
       x__h42892,
       x__h42962,
       x__h4302,
       x__h43574,
       x__h43576,
       x__h43647,
       x__h4369,
       x__h43714,
       x__h44383,
       x__h44385,
       x__h44387,
       x__h44457,
       x__h44524,
       x__h4459,
       x__h44614,
       x__h44743,
       x__h44813,
       x__h45424,
       x__h45426,
       x__h45497,
       x__h45564,
       x__h46234,
       x__h46236,
       x__h46238,
       x__h46308,
       x__h46375,
       x__h46465,
       x__h46594,
       x__h46664,
       x__h4675,
       x__h4809,
       x__h4972,
       x__h5202,
       x__h5204,
       x__h5206,
       x__h5232,
       x__h5274,
       x__h5338,
       x__h5440,
       x__h5507,
       x__h6635,
       x__h6637,
       x__h6639,
       x__h6641,
       x__h6706,
       x__h6770,
       x__h6856,
       x__h7650,
       x__h7652,
       x__h7723,
       x__h7790,
       x__h7895,
       x__h7965,
       x__h9002,
       x__h9004,
       x__h9006,
       x__h9076,
       x__h9143,
       x__h9233,
       x__h9446,
       x__h9643,
       x__h9645,
       x__h9716,
       x__h9783,
       x__h9888,
       x__h9958,
       y__h10014,
       y__h10996,
       y__h10998,
       y__h11000,
       y__h11002,
       y__h11853,
       y__h11855,
       y__h11857,
       y__h12098,
       y__h12100,
       y__h12223,
       y__h13205,
       y__h13207,
       y__h13209,
       y__h13211,
       y__h14088,
       y__h14090,
       y__h14306,
       y__h15414,
       y__h15416,
       y__h15418,
       y__h16610,
       y__h16612,
       y__h16614,
       y__h16857,
       y__h16859,
       y__h16982,
       y__h17968,
       y__h17970,
       y__h17972,
       y__h17974,
       y__h18940,
       y__h18942,
       y__h19151,
       y__h20256,
       y__h20258,
       y__h20260,
       y__h21095,
       y__h21097,
       y__h21099,
       y__h21341,
       y__h21343,
       y__h21466,
       y__h22452,
       y__h22454,
       y__h22456,
       y__h22458,
       y__h25203,
       y__h25400,
       y__h25597,
       y__h25794,
       y__h25991,
       y__h26616,
       y__h26618,
       y__h26834,
       y__h27528,
       y__h27530,
       y__h27532,
       y__h2771,
       y__h2773,
       y__h2775,
       y__h28336,
       y__h28338,
       y__h28340,
       y__h28691,
       y__h28693,
       y__h28816,
       y__h29390,
       y__h29392,
       y__h29394,
       y__h30217,
       y__h30219,
       y__h30221,
       y__h30223,
       y__h30577,
       y__h30579,
       y__h30702,
       y__h3122,
       y__h3124,
       y__h31279,
       y__h31281,
       y__h31283,
       y__h32098,
       y__h32100,
       y__h32102,
       y__h32104,
       y__h32458,
       y__h32460,
       y__h3247,
       y__h32578,
       y__h33447,
       y__h33449,
       y__h33665,
       y__h34342,
       y__h34344,
       y__h34346,
       y__h35133,
       y__h35135,
       y__h35137,
       y__h35488,
       y__h35490,
       y__h35613,
       y__h36170,
       y__h36172,
       y__h36174,
       y__h36980,
       y__h36982,
       y__h36984,
       y__h36986,
       y__h37340,
       y__h37342,
       y__h37465,
       y__h38022,
       y__h38024,
       y__h38026,
       y__h38831,
       y__h38833,
       y__h38835,
       y__h38837,
       y__h39191,
       y__h39193,
       y__h39316,
       y__h39873,
       y__h39875,
       y__h39877,
       y__h40682,
       y__h40684,
       y__h40686,
       y__h40688,
       y__h41042,
       y__h41044,
       y__h41167,
       y__h41724,
       y__h41726,
       y__h41728,
       y__h4229,
       y__h4231,
       y__h4233,
       y__h4235,
       y__h42533,
       y__h42535,
       y__h42537,
       y__h42539,
       y__h42893,
       y__h42895,
       y__h43018,
       y__h43575,
       y__h43577,
       y__h43579,
       y__h44384,
       y__h44386,
       y__h44388,
       y__h44390,
       y__h44744,
       y__h44746,
       y__h44869,
       y__h45425,
       y__h45427,
       y__h45429,
       y__h46235,
       y__h46237,
       y__h46239,
       y__h46241,
       y__h46595,
       y__h46597,
       y__h46720,
       y__h5203,
       y__h5205,
       y__h5207,
       y__h5441,
       y__h5443,
       y__h5561,
       y__h6636,
       y__h6638,
       y__h6640,
       y__h6642,
       y__h7651,
       y__h7653,
       y__h7655,
       y__h7896,
       y__h7898,
       y__h8021,
       y__h9003,
       y__h9005,
       y__h9007,
       y__h9009,
       y__h9644,
       y__h9646,
       y__h9648,
       y__h9889,
       y__h9891;

  // submodule inp
  testinpint8 inp(.rst(RST_N),
		  .CLK(CLK),
		  .cnt(inp$cnt),
		  .EN(inp$EN),
		  .outA(inp$outA),
		  .outB(inp$outB),
		  .outC(inp$outC),
		  .mac(inp$mac));

  // rule RL_comp
  assign WILL_FIRE_RL_comp = (crg_bc ^ 32'h80000000) > 32'h80000006 ;

  // register as1
  assign as1$D_IN = rg_A ;
  assign as1$EN = 1'd1 ;

  // register as2
  assign as2$D_IN = as1 ;
  assign as2$EN = 1'd1 ;

  // register as3
  assign as3$D_IN = as2 ;
  assign as3$EN = 1'd1 ;

  // register as4
  assign as4$D_IN = as3 ;
  assign as4$EN = 1'd1 ;

  // register as5
  assign as5$D_IN = as4 ;
  assign as5$EN = 1'd1 ;

  // register as6
  assign as6$D_IN = as5 ;
  assign as6$EN = 1'd1 ;

  // register bs1
  assign bs1$D_IN = rg_B ;
  assign bs1$EN = 1'd1 ;

  // register bs2
  assign bs2$D_IN = bs1 ;
  assign bs2$EN = 1'd1 ;

  // register bs3
  assign bs3$D_IN = bs2 ;
  assign bs3$EN = 1'd1 ;

  // register bs4
  assign bs4$D_IN = bs3 ;
  assign bs4$EN = 1'd1 ;

  // register bs5
  assign bs5$D_IN = bs4 ;
  assign bs5$EN = 1'd1 ;

  // register bs6
  assign bs6$D_IN = bs5 ;
  assign bs6$EN = 1'd1 ;

  // register crg_bc
  assign crg_bc$D_IN = crg_bc + 32'd1 ;
  assign crg_bc$EN = 1'd1 ;

  // register cs1
  assign cs1$D_IN = rg_C ;
  assign cs1$EN = 1'd1 ;

  // register cs2
  assign cs2$D_IN = cs1 ;
  assign cs2$EN = 1'd1 ;

  // register cs3
  assign cs3$D_IN = cs2 ;
  assign cs3$EN = 1'd1 ;

  // register cs4
  assign cs4$D_IN = cs3 ;
  assign cs4$EN = 1'd1 ;

  // register cs5
  assign cs5$D_IN = cs4 ;
  assign cs5$EN = 1'd1 ;

  // register cs6
  assign cs6$D_IN = cs5 ;
  assign cs6$EN = 1'd1 ;

  // register fail
  assign fail$D_IN = fail + 11'd1 ;
  assign fail$EN =
	     WILL_FIRE_RL_comp &&
	     !obj_mac_rg_stage5_op_023_EQ_s6_MAC_024___d1025 ;

  // register obj_mac_rg_a
  assign obj_mac_rg_a$D_IN = rg_A ;
  assign obj_mac_rg_a$EN = 1'd1 ;

  // register obj_mac_rg_b
  assign obj_mac_rg_b$D_IN = rg_B ;
  assign obj_mac_rg_b$EN = 1'd1 ;

  // register obj_mac_rg_stage1_op_0
  assign obj_mac_rg_stage1_op_0$D_IN =
	     { _0_CONCAT_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_B_ETC___d75,
	       ~x__h2464,
	       x__h4228 | y__h4229,
	       spliced_bits__h2210,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[1:0] } ;
  assign obj_mac_rg_stage1_op_0$EN = 1'd1 ;

  // register obj_mac_rg_stage1_op_1
  assign obj_mac_rg_stage1_op_1$D_IN =
	     { 1'd0,
	       x__h10995 | y__h10996,
	       spliced_bits__h7381,
	       1'd0,
	       x__h9002 | y__h9003,
	       spliced_bits__h7433,
	       spliced_bits__h7329 } ;
  assign obj_mac_rg_stage1_op_1$EN = 1'd1 ;

  // register obj_mac_rg_stage1_op_2
  assign obj_mac_rg_stage1_op_2$D_IN =
	     { 3'd0,
	       ~x__h4972,
	       1'b0,
	       x__h13204 | y__h13205,
	       spliced_bits__h11635,
	       spliced_bits__h11548 } ;
  assign obj_mac_rg_stage1_op_2$EN = 1'd1 ;

  // register obj_mac_rg_stage1_op_3
  assign obj_mac_rg_stage1_op_3$D_IN =
	     { 5'd0,
	       x__h15413 | y__h15414,
	       spliced_bits__h13840,
	       spliced_bits__h13754 } ;
  assign obj_mac_rg_stage1_op_3$EN = 1'd1 ;

  // register obj_mac_rg_stage1_op_4
  assign obj_mac_rg_stage1_op_4$D_IN =
	     { 8'd1,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83[6],
	       7'b0 } ;
  assign obj_mac_rg_stage1_op_4$EN = 1'd1 ;

  // register obj_mac_rg_stage2_op_0
  assign obj_mac_rg_stage2_op_0$D_IN =
	     { 1'd0,
	       obj_mac_rg_stage1_op_0[14],
	       obj_mac_rg_stage1_op_1[13],
	       obj_mac_rg_stage1_op_0[12:9],
	       obj_mac_rg_stage1_op_4[8],
	       x__h17967 | y__h17968,
	       spliced_bits__h16383,
	       obj_mac_rg_stage1_op_0[2:0] } ;
  assign obj_mac_rg_stage2_op_0$EN = 1'd1 ;

  // register obj_mac_rg_stage2_op_1
  assign obj_mac_rg_stage2_op_1$D_IN =
	     { 1'd0,
	       obj_mac_rg_stage1_op_1[14],
	       1'b0,
	       obj_mac_rg_stage1_op_1[12:10],
	       x__h20255 | y__h20256,
	       spliced_bits__h18660,
	       3'd0,
	       obj_mac_rg_stage1_op_1[1],
	       1'b0 } ;
  assign obj_mac_rg_stage2_op_1$EN = 1'd1 ;

  // register obj_mac_rg_stage2_op_2
  assign obj_mac_rg_stage2_op_2$D_IN =
	     { 3'd0,
	       obj_mac_rg_stage1_op_2[12],
	       x__h22451 | y__h22452,
	       spliced_bits__h20875,
	       7'd0 } ;
  assign obj_mac_rg_stage2_op_2$EN = 1'd1 ;

  // register obj_mac_rg_stage3_op_0
  assign obj_mac_rg_stage3_op_0$D_IN =
	     { 1'd0,
	       obj_mac_rg_stage2_op_0[14:13],
	       x__h25992 ^ obj_mac_rg_stage2_op_2[12],
	       x__h25795 ^ obj_mac_rg_stage2_op_2[11],
	       obj_mac_rg_stage2_op_0_62_BIT_10_77_XOR_obj_ma_ETC___d496,
	       obj_mac_rg_stage2_op_0[6:0] } ;
  assign obj_mac_rg_stage3_op_0$EN = 1'd1 ;

  // register obj_mac_rg_stage3_op_1
  assign obj_mac_rg_stage3_op_1$D_IN =
	     { 1'd1,
	       obj_mac_rg_stage2_op_1[14],
	       obj_mac_rg_stage2_op_0_62_BIT_12_65_AND_obj_ma_ETC___d520,
	       spliced_bits__h24729 } ;
  assign obj_mac_rg_stage3_op_1$EN = 1'd1 ;

  // register obj_mac_rg_stage4_op
  assign obj_mac_rg_stage4_op$D_IN =
	     { spliced_bits__h26311,
	       spliced_bits__h26339,
	       spliced_bits__h26367,
	       spliced_bits__h26395 } ;
  assign obj_mac_rg_stage4_op$EN = 1'd1 ;

  // register obj_mac_rg_stage5_op
  assign obj_mac_rg_stage5_op$D_IN =
	     { spliced_bits__h33044,
	       spliced_bits__h33072,
	       spliced_bits__h33100,
	       spliced_bits__h33128,
	       spliced_bits__h33156,
	       spliced_bits__h33184,
	       spliced_bits__h33212,
	       spliced_bits__h33240 } ;
  assign obj_mac_rg_stage5_op$EN = 1'd1 ;

  // register obj_mac_s1_a
  assign obj_mac_s1_a$D_IN = 8'h0 ;
  assign obj_mac_s1_a$EN = 1'b0 ;

  // register obj_mac_s1_b
  assign obj_mac_s1_b$D_IN = 8'h0 ;
  assign obj_mac_s1_b$EN = 1'b0 ;

  // register obj_mac_s1_c
  assign obj_mac_s1_c$D_IN = rg_C ;
  assign obj_mac_s1_c$EN = 1'd1 ;

  // register obj_mac_s2_a
  assign obj_mac_s2_a$D_IN = obj_mac_rg_a ;
  assign obj_mac_s2_a$EN = 1'd1 ;

  // register obj_mac_s2_b
  assign obj_mac_s2_b$D_IN = obj_mac_rg_b ;
  assign obj_mac_s2_b$EN = 1'd1 ;

  // register obj_mac_s2_c
  assign obj_mac_s2_c$D_IN = obj_mac_s1_c ;
  assign obj_mac_s2_c$EN = 1'd1 ;

  // register obj_mac_s3_a
  assign obj_mac_s3_a$D_IN = obj_mac_s2_a ;
  assign obj_mac_s3_a$EN = 1'd1 ;

  // register obj_mac_s3_b
  assign obj_mac_s3_b$D_IN = obj_mac_s2_b ;
  assign obj_mac_s3_b$EN = 1'd1 ;

  // register obj_mac_s3_c
  assign obj_mac_s3_c$D_IN = obj_mac_s2_c ;
  assign obj_mac_s3_c$EN = 1'd1 ;

  // register obj_mac_s4_a
  assign obj_mac_s4_a$D_IN = obj_mac_s3_a ;
  assign obj_mac_s4_a$EN = 1'd1 ;

  // register obj_mac_s4_b
  assign obj_mac_s4_b$D_IN = obj_mac_s3_b ;
  assign obj_mac_s4_b$EN = 1'd1 ;

  // register obj_mac_s4_c
  assign obj_mac_s4_c$D_IN = obj_mac_s3_c ;
  assign obj_mac_s4_c$EN = 1'd1 ;

  // register obj_mac_s5_a
  assign obj_mac_s5_a$D_IN = obj_mac_s4_a ;
  assign obj_mac_s5_a$EN = 1'd1 ;

  // register obj_mac_s5_b
  assign obj_mac_s5_b$D_IN = obj_mac_s4_b ;
  assign obj_mac_s5_b$EN = 1'd1 ;

  // register obj_mac_s5_c
  assign obj_mac_s5_c$D_IN = obj_mac_s4_c ;
  assign obj_mac_s5_c$EN = 1'd1 ;

  // register rg_A
  assign rg_A$D_IN = inp$outA ;
  assign rg_A$EN = 1'd1 ;

  // register rg_B
  assign rg_B$D_IN = inp$outB ;
  assign rg_B$EN = 1'd1 ;

  // register rg_C
  assign rg_C$D_IN = inp$outC ;
  assign rg_C$EN = 1'd1 ;

  // register rg_MAC
  assign rg_MAC$D_IN = inp$mac ;
  assign rg_MAC$EN = 1'd1 ;

  // register s1_MAC
  assign s1_MAC$D_IN = rg_MAC ;
  assign s1_MAC$EN = 1'd1 ;

  // register s2_MAC
  assign s2_MAC$D_IN = s1_MAC ;
  assign s2_MAC$EN = 1'd1 ;

  // register s3_MAC
  assign s3_MAC$D_IN = s2_MAC ;
  assign s3_MAC$EN = 1'd1 ;

  // register s4_MAC
  assign s4_MAC$D_IN = s3_MAC ;
  assign s4_MAC$EN = 1'd1 ;

  // register s5_MAC
  assign s5_MAC$D_IN = s4_MAC ;
  assign s5_MAC$EN = 1'd1 ;

  // register s6_MAC
  assign s6_MAC$D_IN = s5_MAC ;
  assign s6_MAC$EN = 1'd1 ;

  // submodule inp
  assign inp$cnt = 11'd1048 ;
  assign inp$EN = 1'd1 ;

  // remaining internal signals
  assign IF_x5132_OR_y5133_THEN_1_ELSE_0__q3 =
	     (x__h35132 | y__h35133) ? 8'd1 : 8'd0 ;
  assign IF_x8335_OR_y8336_THEN_1_ELSE_0__q2 =
	     (x__h28335 | y__h28336) ? 4'd1 : 4'd0 ;
  assign INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38 =
	     { ~x__h3015,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[6] } &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36[6:5] ;
  assign INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42 =
	     { ~x__h3015,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[6] } ^
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36[6:5] ;
  assign INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d73 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42 ^
	     { INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[0] |
	       y__h5561,
	       cin__h4622 } ;
  assign INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_4__ETC___d16 =
	     ~x__h4675 ^
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[6] ;
  assign INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139 =
	     rg_a__h10422 & INV_x073__q1[6:3] ;
  assign INV_x073__q1 = ~x__h7073 ;
  assign SEXT_obj_mac_rg_stage4_op_81___d682 =
	     { {16{obj_mac_rg_stage4_op[15]}}, obj_mac_rg_stage4_op } ;
  assign _0_CONCAT_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_B_ETC___d75 =
	     { 1'd0,
	       obj_mac_rg_a[7] & obj_mac_rg_b[7],
	       1'b0,
	       x__h6635 | y__h6636,
	       spliced_bits__h2158 } ;
  assign cin__h29245 = x__h30216 | y__h30217 ;
  assign cin__h31131 = x__h32097 | y__h32098 ;
  assign cin__h36041 = x__h36979 | y__h36980 ;
  assign cin__h37893 = x__h38830 | y__h38831 ;
  assign cin__h39744 = x__h40681 | y__h40682 ;
  assign cin__h41595 = x__h42532 | y__h42533 ;
  assign cin__h43446 = x__h44383 | y__h44384 ;
  assign cin__h45296 = x__h46234 | y__h46235 ;
  assign cin__h4622 = ~x__h2598 ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[5]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d132 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[6]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[5:2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36[4:1] ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[4]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[5:2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[4:1] ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d132[3:0] &
	     rg_b__h13914 ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[2]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[3]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[0]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83 =
	     obj_mac_rg_a[6:0] & {7{obj_mac_rg_b[1]}} ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[5:2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83[4:1] ;
  assign obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[5:2] ^
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83[4:1] ;
  assign obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328 =
	     obj_mac_rg_stage1_op_0[6:3] & obj_mac_rg_stage1_op_1[6:3] ;
  assign obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330 =
	     obj_mac_rg_stage1_op_0[6:3] ^ obj_mac_rg_stage1_op_1[6:3] ;
  assign obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_AND_o_ETC___d377 =
	     obj_mac_rg_stage1_op_0[8:7] & obj_mac_rg_stage1_op_1[8:7] ;
  assign obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379 =
	     obj_mac_rg_stage1_op_0[8:7] ^ obj_mac_rg_stage1_op_1[8:7] ;
  assign obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417 =
	     obj_mac_rg_stage1_op_2[10:7] & obj_mac_rg_stage1_op_3[10:7] ;
  assign obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419 =
	     obj_mac_rg_stage1_op_2[10:7] ^ obj_mac_rg_stage1_op_3[10:7] ;
  assign obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389 =
	     obj_mac_rg_stage1_op_2[6:5] & obj_mac_rg_stage1_op_3[6:5] ;
  assign obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_XOR_o_ETC___d393 =
	     obj_mac_rg_stage1_op_2[6:5] ^ obj_mac_rg_stage1_op_3[6:5] ;
  assign obj_mac_rg_stage2_op_0_62_BIT_10_77_AND_obj_ma_ETC___d519 =
	     { x__h25596 | y__h25597,
	       x__h25399 | y__h25400,
	       x__h25202 | y__h25203,
	       obj_mac_rg_stage2_op_0[7] & obj_mac_rg_stage2_op_1[7] } ;
  assign obj_mac_rg_stage2_op_0_62_BIT_10_77_XOR_obj_ma_ETC___d496 =
	     { x__h25598 ^ obj_mac_rg_stage2_op_2[10],
	       x__h25401 ^ obj_mac_rg_stage2_op_2[9],
	       x__h25204 ^ obj_mac_rg_stage2_op_2[8],
	       obj_mac_rg_stage2_op_0[7] ^ obj_mac_rg_stage2_op_1[7] } ;
  assign obj_mac_rg_stage2_op_0_62_BIT_12_65_AND_obj_ma_ETC___d520 =
	     { x__h25990 | y__h25991,
	       x__h25793 | y__h25794,
	       obj_mac_rg_stage2_op_0_62_BIT_10_77_AND_obj_ma_ETC___d519 } ;
  assign obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550 =
	     obj_mac_rg_stage3_op_0[11:8] & obj_mac_rg_stage3_op_1[11:8] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552 =
	     obj_mac_rg_stage3_op_0[11:8] ^ obj_mac_rg_stage3_op_1[11:8] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534 =
	     obj_mac_rg_stage3_op_0[14:12] & obj_mac_rg_stage3_op_1[14:12] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d625 =
	     { x__h32457 | y__h32458,
	       obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534[0] |
	       y__h32578,
	       cin__h31131 } ;
  assign obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536 =
	     obj_mac_rg_stage3_op_0[14:12] ^ obj_mac_rg_stage3_op_1[14:12] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592 =
	     obj_mac_rg_stage3_op_0[3:0] & obj_mac_rg_stage3_op_1[3:0] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594 =
	     obj_mac_rg_stage3_op_0[3:0] ^ obj_mac_rg_stage3_op_1[3:0] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571 =
	     obj_mac_rg_stage3_op_0[7:4] & obj_mac_rg_stage3_op_1[7:4] ;
  assign obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573 =
	     obj_mac_rg_stage3_op_0[7:4] ^ obj_mac_rg_stage3_op_1[7:4] ;
  assign obj_mac_rg_stage5_op_023_EQ_s6_MAC_024___d1025 =
	     obj_mac_rg_stage5_op == s6_MAC ;
  assign obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784 =
	     obj_mac_s5_c[11:8] & SEXT_obj_mac_rg_stage4_op_81___d682[11:8] ;
  assign obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763 =
	     obj_mac_s5_c[15:12] &
	     SEXT_obj_mac_rg_stage4_op_81___d682[15:12] ;
  assign obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742 =
	     obj_mac_s5_c[19:16] &
	     SEXT_obj_mac_rg_stage4_op_81___d682[19:16] ;
  assign obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721 =
	     obj_mac_s5_c[23:20] &
	     SEXT_obj_mac_rg_stage4_op_81___d682[23:20] ;
  assign obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700 =
	     obj_mac_s5_c[27:24] &
	     SEXT_obj_mac_rg_stage4_op_81___d682[27:24] ;
  assign obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685 =
	     obj_mac_s5_c[31:28] &
	     SEXT_obj_mac_rg_stage4_op_81___d682[31:28] ;
  assign obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826 =
	     obj_mac_s5_c[3:0] & SEXT_obj_mac_rg_stage4_op_81___d682[3:0] ;
  assign obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828 =
	     obj_mac_s5_c[3:0] ^ SEXT_obj_mac_rg_stage4_op_81___d682[3:0] ;
  assign obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805 =
	     obj_mac_s5_c[7:4] & SEXT_obj_mac_rg_stage4_op_81___d682[7:4] ;
  assign p__h11717 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[5:2] ^
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[4:1] ;
  assign p__h13921 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d132[3:0] ^
	     rg_b__h13914 ;
  assign p__h18741 =
	     { obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379,
	       obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_XOR_o_ETC___d393 } ;
  assign p__h34220 =
	     obj_mac_s5_c[7:4] ^ SEXT_obj_mac_rg_stage4_op_81___d682[7:4] ;
  assign p__h36048 =
	     obj_mac_s5_c[11:8] ^ SEXT_obj_mac_rg_stage4_op_81___d682[11:8] ;
  assign p__h37900 =
	     obj_mac_s5_c[15:12] ^
	     SEXT_obj_mac_rg_stage4_op_81___d682[15:12] ;
  assign p__h39751 =
	     obj_mac_s5_c[19:16] ^
	     SEXT_obj_mac_rg_stage4_op_81___d682[19:16] ;
  assign p__h41602 =
	     obj_mac_s5_c[23:20] ^
	     SEXT_obj_mac_rg_stage4_op_81___d682[23:20] ;
  assign p__h43453 =
	     obj_mac_s5_c[27:24] ^
	     SEXT_obj_mac_rg_stage4_op_81___d682[27:24] ;
  assign p__h45303 =
	     obj_mac_s5_c[31:28] ^
	     SEXT_obj_mac_rg_stage4_op_81___d682[31:28] ;
  assign p__h7515 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[5:2] ^
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36[4:1] ;
  assign p__h9402 = rg_a__h10422 ^ INV_x073__q1[6:3] ;
  assign rg_a__h10422 =
	     { ~x__h9446,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d132[6:4] } ;
  assign rg_b__h13914 =
	     { INV_x073__q1[2:0],
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83[5] } ;
  assign spliced_bits__h11548 =
	     { obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[1],
	       1'b0,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d36[0],
	       3'b0 } ;
  assign spliced_bits__h11635 = p__h11717 ^ y__h11721 ;
  assign spliced_bits__h13754 =
	     { obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[0],
	       5'b0 } ;
  assign spliced_bits__h13840 = p__h13921 ^ y__h13925 ;
  assign spliced_bits__h16383 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330 ^
	     y__h16474 ;
  assign spliced_bits__h18660 = p__h18741 ^ y__h18745 ;
  assign spliced_bits__h20875 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419 ^
	     y__h20961 ;
  assign spliced_bits__h2158 =
	     { INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_4__ETC___d16 ^
	       (x__h5202 | y__h5203),
	       x__h5232 ^ (x__h5440 | y__h5441),
	       INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d73 } ;
  assign spliced_bits__h2210 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87 ^
	     y__h2302 ;
  assign spliced_bits__h24729 =
	     { obj_mac_rg_stage2_op_2[7],
	       obj_mac_rg_stage2_op_1[6:5],
	       3'b0,
	       obj_mac_rg_stage2_op_1[1],
	       1'b0 } ;
  assign spliced_bits__h26311 =
	     { ~(x__h31278 | y__h31279),
	       obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536 ^
	       obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d625 } ;
  assign spliced_bits__h26339 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552 ^
	     y__h29256 ;
  assign spliced_bits__h26367 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573 ^
	     y__h27394 ;
  assign spliced_bits__h26395 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594 ^
	     y__h26478 ;
  assign spliced_bits__h33044 = p__h45303 ^ y__h45307 ;
  assign spliced_bits__h33072 = p__h43453 ^ y__h43457 ;
  assign spliced_bits__h33100 = p__h41602 ^ y__h41606 ;
  assign spliced_bits__h33128 = p__h39751 ^ y__h39755 ;
  assign spliced_bits__h33156 = p__h37900 ^ y__h37904 ;
  assign spliced_bits__h33184 = p__h36048 ^ y__h36052 ;
  assign spliced_bits__h33212 = p__h34220 ^ y__h34224 ;
  assign spliced_bits__h33240 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828 ^
	     y__h33322 ;
  assign spliced_bits__h7329 =
	     { obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[1],
	       1'b0,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d83[0],
	       1'b0 } ;
  assign spliced_bits__h7381 = p__h9402 ^ y__h9406 ;
  assign spliced_bits__h7433 = p__h7515 ^ y__h7519 ;
  assign x__h10995 = x__h10997 | y__h10998 ;
  assign x__h10997 = x__h10999 | y__h11000 ;
  assign x__h10999 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[3] |
	     y__h11002 ;
  assign x__h11069 = p__h9402[3] & p__h9402[2] ;
  assign x__h11136 = x__h11069 & p__h9402[1] ;
  assign x__h11226 = x__h11136 & p__h9402[0] ;
  assign x__h11852 = x__h11854 | y__h11855 ;
  assign x__h11854 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[2] |
	     y__h11857 ;
  assign x__h11925 = p__h11717[2] & p__h11717[1] ;
  assign x__h11992 = x__h11925 & p__h11717[0] ;
  assign x__h12097 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[1] |
	     y__h12100 ;
  assign x__h12167 = p__h11717[1] & p__h11717[0] ;
  assign x__h13204 = x__h13206 | y__h13207 ;
  assign x__h13206 = x__h13208 | y__h13209 ;
  assign x__h13208 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[3] |
	     y__h13211 ;
  assign x__h13278 = p__h11717[3] & p__h11717[2] ;
  assign x__h13345 = x__h13278 & p__h11717[1] ;
  assign x__h13435 = x__h13345 & p__h11717[0] ;
  assign x__h14087 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[2] |
	     y__h14090 ;
  assign x__h14158 = p__h13921[2] & p__h13921[1] ;
  assign x__h15413 = x__h15415 | y__h15416 ;
  assign x__h15415 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[3] |
	     y__h15418 ;
  assign x__h15485 = p__h13921[3] & p__h13921[2] ;
  assign x__h15552 = x__h15485 & p__h13921[1] ;
  assign x__h16609 = x__h16611 | y__h16612 ;
  assign x__h16611 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[2] |
	     y__h16614 ;
  assign x__h16682 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[2] &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[1] ;
  assign x__h16749 =
	     x__h16682 &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[0] ;
  assign x__h16856 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[1] |
	     y__h16859 ;
  assign x__h16926 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[1] &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[0] ;
  assign x__h17967 = x__h17969 | y__h17970 ;
  assign x__h17969 = x__h17971 | y__h17972 ;
  assign x__h17971 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[3] |
	     y__h17974 ;
  assign x__h18041 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[3] &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[2] ;
  assign x__h18108 =
	     x__h18041 &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[1] ;
  assign x__h18198 =
	     x__h18108 &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[0] ;
  assign x__h18939 =
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_AND_o_ETC___d377[0] |
	     y__h18942 ;
  assign x__h19009 =
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379[0] &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_XOR_o_ETC___d393[1] ;
  assign x__h20255 = x__h20257 | y__h20258 ;
  assign x__h20257 =
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_AND_o_ETC___d377[1] |
	     y__h20260 ;
  assign x__h20324 =
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379[1] &
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379[0] ;
  assign x__h20388 =
	     x__h20324 &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_XOR_o_ETC___d393[1] ;
  assign x__h21094 = x__h21096 | y__h21097 ;
  assign x__h21096 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[2] |
	     y__h21099 ;
  assign x__h21167 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[2] &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[1] ;
  assign x__h21234 =
	     x__h21167 &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[0] ;
  assign x__h21340 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[1] |
	     y__h21343 ;
  assign x__h21410 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[1] &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[0] ;
  assign x__h22451 = x__h22453 | y__h22454 ;
  assign x__h22453 = x__h22455 | y__h22456 ;
  assign x__h22455 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[3] |
	     y__h22458 ;
  assign x__h22525 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[3] &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[2] ;
  assign x__h22592 =
	     x__h22525 &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[1] ;
  assign x__h22682 =
	     x__h22592 &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[0] ;
  assign x__h2464 = obj_mac_rg_a[7] & obj_mac_rg_b[0] ;
  assign x__h25202 = obj_mac_rg_stage2_op_0[8] & obj_mac_rg_stage2_op_1[8] ;
  assign x__h25204 = obj_mac_rg_stage2_op_0[8] ^ obj_mac_rg_stage2_op_1[8] ;
  assign x__h25399 = obj_mac_rg_stage2_op_0[9] & obj_mac_rg_stage2_op_1[9] ;
  assign x__h25401 = obj_mac_rg_stage2_op_0[9] ^ obj_mac_rg_stage2_op_1[9] ;
  assign x__h25596 = obj_mac_rg_stage2_op_0[10] & obj_mac_rg_stage2_op_1[10] ;
  assign x__h25598 = obj_mac_rg_stage2_op_0[10] ^ obj_mac_rg_stage2_op_1[10] ;
  assign x__h25793 = obj_mac_rg_stage2_op_0[11] & obj_mac_rg_stage2_op_1[11] ;
  assign x__h25795 = obj_mac_rg_stage2_op_0[11] ^ obj_mac_rg_stage2_op_1[11] ;
  assign x__h2598 = obj_mac_rg_a[7] & obj_mac_rg_b[1] ;
  assign x__h25990 = obj_mac_rg_stage2_op_0[12] & obj_mac_rg_stage2_op_1[12] ;
  assign x__h25992 = obj_mac_rg_stage2_op_0[12] ^ obj_mac_rg_stage2_op_1[12] ;
  assign x__h26615 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[2] |
	     y__h26618 ;
  assign x__h26686 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[1] ;
  assign x__h27527 = x__h27529 | y__h27530 ;
  assign x__h27529 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[2] |
	     y__h27532 ;
  assign x__h27600 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[1] ;
  assign x__h27667 =
	     x__h27600 &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[0] ;
  assign x__h2770 = x__h2772 | y__h2773 ;
  assign x__h2772 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[2] |
	     y__h2775 ;
  assign x__h28335 = x__h28337 | y__h28338 ;
  assign x__h28337 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[3] |
	     y__h28340 ;
  assign x__h28407 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[3] &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[2] ;
  assign x__h2843 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[1] ;
  assign x__h28474 =
	     x__h28407 &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[1] ;
  assign x__h28690 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[1] |
	     y__h28693 ;
  assign x__h28760 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[0] ;
  assign x__h2910 =
	     x__h2843 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[0] ;
  assign x__h29389 = x__h29391 | y__h29392 ;
  assign x__h29391 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[2] |
	     y__h29394 ;
  assign x__h29462 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[1] ;
  assign x__h29529 =
	     x__h29462 &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[0] ;
  assign x__h3015 = obj_mac_rg_a[7] & obj_mac_rg_b[2] ;
  assign x__h30216 = x__h30218 | y__h30219 ;
  assign x__h30218 = x__h30220 | y__h30221 ;
  assign x__h30220 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[3] |
	     y__h30223 ;
  assign x__h30290 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[3] &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[2] ;
  assign x__h30357 =
	     x__h30290 &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[1] ;
  assign x__h30447 =
	     x__h30357 &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[0] ;
  assign x__h30576 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[1] |
	     y__h30579 ;
  assign x__h30646 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[0] ;
  assign x__h3121 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[1] |
	     y__h3124 ;
  assign x__h31278 = x__h31280 | y__h31281 ;
  assign x__h31280 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534[2] |
	     y__h31283 ;
  assign x__h31349 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[1] ;
  assign x__h31413 =
	     x__h31349 &
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[0] ;
  assign x__h3191 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[1] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[0] ;
  assign x__h32097 = x__h32099 | y__h32100 ;
  assign x__h32099 = x__h32101 | y__h32102 ;
  assign x__h32101 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[3] |
	     y__h32104 ;
  assign x__h32171 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[3] &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[2] ;
  assign x__h32238 =
	     x__h32171 &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[1] ;
  assign x__h32328 =
	     x__h32238 &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[0] ;
  assign x__h32457 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534[1] |
	     y__h32460 ;
  assign x__h32524 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[0] ;
  assign x__h33446 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[2] |
	     y__h33449 ;
  assign x__h33517 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[2] &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[1] ;
  assign x__h34341 = x__h34343 | y__h34344 ;
  assign x__h34343 =
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[2] |
	     y__h34346 ;
  assign x__h34414 = p__h34220[2] & p__h34220[1] ;
  assign x__h34481 = x__h34414 & p__h34220[0] ;
  assign x__h35132 = x__h35134 | y__h35135 ;
  assign x__h35134 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[3] |
	     y__h35137 ;
  assign x__h35204 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[3] &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[2] ;
  assign x__h35271 =
	     x__h35204 &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[1] ;
  assign x__h35487 =
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[1] |
	     y__h35490 ;
  assign x__h35557 = p__h34220[1] & p__h34220[0] ;
  assign x__h36169 = x__h36171 | y__h36172 ;
  assign x__h36171 =
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[2] |
	     y__h36174 ;
  assign x__h36242 = p__h36048[2] & p__h36048[1] ;
  assign x__h36309 = x__h36242 & p__h36048[0] ;
  assign x__h36979 = x__h36981 | y__h36982 ;
  assign x__h36981 = x__h36983 | y__h36984 ;
  assign x__h36983 =
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[3] |
	     y__h36986 ;
  assign x__h37053 = p__h34220[3] & p__h34220[2] ;
  assign x__h37120 = x__h37053 & p__h34220[1] ;
  assign x__h37210 = x__h37120 & p__h34220[0] ;
  assign x__h37339 =
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[1] |
	     y__h37342 ;
  assign x__h37409 = p__h36048[1] & p__h36048[0] ;
  assign x__h38021 = x__h38023 | y__h38024 ;
  assign x__h38023 =
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[2] |
	     y__h38026 ;
  assign x__h38094 = p__h37900[2] & p__h37900[1] ;
  assign x__h38161 = x__h38094 & p__h37900[0] ;
  assign x__h38830 = x__h38832 | y__h38833 ;
  assign x__h38832 = x__h38834 | y__h38835 ;
  assign x__h38834 =
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[3] |
	     y__h38837 ;
  assign x__h38904 = p__h36048[3] & p__h36048[2] ;
  assign x__h38971 = x__h38904 & p__h36048[1] ;
  assign x__h39061 = x__h38971 & p__h36048[0] ;
  assign x__h39190 =
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[1] |
	     y__h39193 ;
  assign x__h39260 = p__h37900[1] & p__h37900[0] ;
  assign x__h39872 = x__h39874 | y__h39875 ;
  assign x__h39874 =
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[2] |
	     y__h39877 ;
  assign x__h39945 = p__h39751[2] & p__h39751[1] ;
  assign x__h40012 = x__h39945 & p__h39751[0] ;
  assign x__h40681 = x__h40683 | y__h40684 ;
  assign x__h40683 = x__h40685 | y__h40686 ;
  assign x__h40685 =
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[3] |
	     y__h40688 ;
  assign x__h40755 = p__h37900[3] & p__h37900[2] ;
  assign x__h40822 = x__h40755 & p__h37900[1] ;
  assign x__h40912 = x__h40822 & p__h37900[0] ;
  assign x__h41041 =
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[1] |
	     y__h41044 ;
  assign x__h41111 = p__h39751[1] & p__h39751[0] ;
  assign x__h41723 = x__h41725 | y__h41726 ;
  assign x__h41725 =
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[2] |
	     y__h41728 ;
  assign x__h41796 = p__h41602[2] & p__h41602[1] ;
  assign x__h41863 = x__h41796 & p__h41602[0] ;
  assign x__h4228 = x__h4230 | y__h4231 ;
  assign x__h4230 = x__h4232 | y__h4233 ;
  assign x__h4232 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[3] |
	     y__h4235 ;
  assign x__h42532 = x__h42534 | y__h42535 ;
  assign x__h42534 = x__h42536 | y__h42537 ;
  assign x__h42536 =
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[3] |
	     y__h42539 ;
  assign x__h42606 = p__h39751[3] & p__h39751[2] ;
  assign x__h42673 = x__h42606 & p__h39751[1] ;
  assign x__h42763 = x__h42673 & p__h39751[0] ;
  assign x__h42892 =
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[1] |
	     y__h42895 ;
  assign x__h42962 = p__h41602[1] & p__h41602[0] ;
  assign x__h4302 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[3] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[2] ;
  assign x__h43574 = x__h43576 | y__h43577 ;
  assign x__h43576 =
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[2] |
	     y__h43579 ;
  assign x__h43647 = p__h43453[2] & p__h43453[1] ;
  assign x__h4369 =
	     x__h4302 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[1] ;
  assign x__h43714 = x__h43647 & p__h43453[0] ;
  assign x__h44383 = x__h44385 | y__h44386 ;
  assign x__h44385 = x__h44387 | y__h44388 ;
  assign x__h44387 =
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[3] |
	     y__h44390 ;
  assign x__h44457 = p__h41602[3] & p__h41602[2] ;
  assign x__h44524 = x__h44457 & p__h41602[1] ;
  assign x__h4459 =
	     x__h4369 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[0] ;
  assign x__h44614 = x__h44524 & p__h41602[0] ;
  assign x__h44743 =
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[1] |
	     y__h44746 ;
  assign x__h44813 = p__h43453[1] & p__h43453[0] ;
  assign x__h45424 = x__h45426 | y__h45427 ;
  assign x__h45426 =
	     obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685[2] |
	     y__h45429 ;
  assign x__h45497 = p__h45303[2] & p__h45303[1] ;
  assign x__h45564 = x__h45497 & p__h45303[0] ;
  assign x__h46234 = x__h46236 | y__h46237 ;
  assign x__h46236 = x__h46238 | y__h46239 ;
  assign x__h46238 =
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[3] |
	     y__h46241 ;
  assign x__h46308 = p__h43453[3] & p__h43453[2] ;
  assign x__h46375 = x__h46308 & p__h43453[1] ;
  assign x__h46465 = x__h46375 & p__h43453[0] ;
  assign x__h46594 =
	     obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685[1] |
	     y__h46597 ;
  assign x__h46664 = p__h45303[1] & p__h45303[0] ;
  assign x__h4675 = obj_mac_rg_a[7] & obj_mac_rg_b[4] ;
  assign x__h4809 = obj_mac_rg_a[7] & obj_mac_rg_b[3] ;
  assign x__h4972 = obj_mac_rg_a[7] & obj_mac_rg_b[5] ;
  assign x__h5202 = x__h5204 | y__h5205 ;
  assign x__h5204 = x__h5206 | y__h5207 ;
  assign x__h5206 =
	     ~x__h4809 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[6] ;
  assign x__h5232 =
	     ~x__h4809 ^
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[6] ;
  assign x__h5274 =
	     x__h5232 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[1] ;
  assign x__h5338 =
	     x__h5274 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[0] ;
  assign x__h5440 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[1] |
	     y__h5443 ;
  assign x__h5507 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[1] &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[0] ;
  assign x__h6635 = x__h6637 | y__h6638 ;
  assign x__h6637 = x__h6639 | y__h6640 ;
  assign x__h6639 = x__h6641 | y__h6642 ;
  assign x__h6641 =
	     ~x__h4675 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[6] ;
  assign x__h6706 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_4__ETC___d16 &
	     x__h5232 ;
  assign x__h6770 =
	     x__h6706 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[1] ;
  assign x__h6856 =
	     x__h6770 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[0] ;
  assign x__h7073 = obj_mac_rg_a[6:0] & y__h7075 ;
  assign x__h7650 = x__h7652 | y__h7653 ;
  assign x__h7652 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[2] |
	     y__h7655 ;
  assign x__h7723 = p__h7515[2] & p__h7515[1] ;
  assign x__h7790 = x__h7723 & p__h7515[0] ;
  assign x__h7895 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[1] |
	     y__h7898 ;
  assign x__h7965 = p__h7515[1] & p__h7515[0] ;
  assign x__h9002 = x__h9004 | y__h9005 ;
  assign x__h9004 = x__h9006 | y__h9007 ;
  assign x__h9006 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[3] |
	     y__h9009 ;
  assign x__h9076 = p__h7515[3] & p__h7515[2] ;
  assign x__h9143 = x__h9076 & p__h7515[1] ;
  assign x__h9233 = x__h9143 & p__h7515[0] ;
  assign x__h9446 = obj_mac_rg_a[7] & obj_mac_rg_b[6] ;
  assign x__h9643 = x__h9645 | y__h9646 ;
  assign x__h9645 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[2] |
	     y__h9648 ;
  assign x__h9716 = p__h9402[2] & p__h9402[1] ;
  assign x__h9783 = x__h9716 & p__h9402[0] ;
  assign x__h9888 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[1] |
	     y__h9891 ;
  assign x__h9958 = p__h9402[1] & p__h9402[0] ;
  assign y__h10014 =
	     p__h9402[0] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[5] ;
  assign y__h10996 =
	     x__h11226 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[5] ;
  assign y__h10998 =
	     x__h11136 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[0] ;
  assign y__h11000 =
	     x__h11069 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[1] ;
  assign y__h11002 =
	     p__h9402[3] &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[2] ;
  assign y__h11721 =
	     { x__h11852 | y__h11853,
	       x__h12097 | y__h12098,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[0] |
	       y__h12223,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[6] } ;
  assign y__h11853 =
	     x__h11992 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[6] ;
  assign y__h11855 =
	     x__h11925 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[0] ;
  assign y__h11857 =
	     p__h11717[2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[1] ;
  assign y__h12098 =
	     x__h12167 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[6] ;
  assign y__h12100 =
	     p__h11717[1] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[0] ;
  assign y__h12223 =
	     p__h11717[0] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[6] ;
  assign y__h13205 =
	     x__h13435 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d80[6] ;
  assign y__h13207 =
	     x__h13345 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[0] ;
  assign y__h13209 =
	     x__h13278 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[1] ;
  assign y__h13211 =
	     p__h11717[3] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d233[2] ;
  assign y__h13925 =
	     { x__h14087 | y__h14088,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[1] |
	       y__h14306,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[0],
	       1'b0 } ;
  assign y__h14088 =
	     x__h14158 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[0] ;
  assign y__h14090 =
	     p__h13921[2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[1] ;
  assign y__h14306 =
	     p__h13921[1] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[0] ;
  assign y__h15414 =
	     x__h15552 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[0] ;
  assign y__h15416 =
	     x__h15485 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[1] ;
  assign y__h15418 =
	     p__h13921[3] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d283[2] ;
  assign y__h16474 =
	     { x__h16609 | y__h16610,
	       x__h16856 | y__h16857,
	       obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[0] |
	       y__h16982,
	       obj_mac_rg_stage1_op_2[3] } ;
  assign y__h16610 = x__h16749 & obj_mac_rg_stage1_op_2[3] ;
  assign y__h16612 =
	     x__h16682 &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[0] ;
  assign y__h16614 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[2] &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[1] ;
  assign y__h16857 = x__h16926 & obj_mac_rg_stage1_op_2[3] ;
  assign y__h16859 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[1] &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[0] ;
  assign y__h16982 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[0] &
	     obj_mac_rg_stage1_op_2[3] ;
  assign y__h17968 = x__h18198 & obj_mac_rg_stage1_op_2[3] ;
  assign y__h17970 =
	     x__h18108 &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[0] ;
  assign y__h17972 =
	     x__h18041 &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[1] ;
  assign y__h17974 =
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_XOR_o_ETC___d330[3] &
	     obj_mac_rg_stage1_op_0_17_BITS_6_TO_3_26_AND_o_ETC___d328[2] ;
  assign y__h18745 =
	     { x__h18939 | y__h18940,
	       obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[1] |
	       y__h19151,
	       obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[0],
	       1'b0 } ;
  assign y__h18940 =
	     x__h19009 &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[0] ;
  assign y__h18942 =
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379[0] &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[1] ;
  assign y__h19151 =
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_XOR_o_ETC___d393[1] &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[0] ;
  assign y__h20256 =
	     x__h20388 &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[0] ;
  assign y__h20258 =
	     x__h20324 &
	     obj_mac_rg_stage1_op_2_47_BITS_6_TO_5_86_AND_o_ETC___d389[1] ;
  assign y__h20260 =
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_XOR_o_ETC___d379[1] &
	     obj_mac_rg_stage1_op_0_17_BITS_8_TO_7_75_AND_o_ETC___d377[0] ;
  assign y__h20961 =
	     { x__h21094 | y__h21095,
	       x__h21340 | y__h21341,
	       obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[0] |
	       y__h21466,
	       obj_mac_rg_stage1_op_4[7] } ;
  assign y__h21095 = x__h21234 & obj_mac_rg_stage1_op_4[7] ;
  assign y__h21097 =
	     x__h21167 &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[0] ;
  assign y__h21099 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[2] &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[1] ;
  assign y__h21341 = x__h21410 & obj_mac_rg_stage1_op_4[7] ;
  assign y__h21343 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[1] &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[0] ;
  assign y__h21466 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[0] &
	     obj_mac_rg_stage1_op_4[7] ;
  assign y__h22452 = x__h22682 & obj_mac_rg_stage1_op_4[7] ;
  assign y__h22454 =
	     x__h22592 &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[0] ;
  assign y__h22456 =
	     x__h22525 &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[1] ;
  assign y__h22458 =
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_XOR__ETC___d419[3] &
	     obj_mac_rg_stage1_op_2_47_BITS_10_TO_7_15_AND__ETC___d417[2] ;
  assign y__h2302 =
	     { x__h2770 | y__h2771,
	       x__h3121 | y__h3122,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[0] |
	       y__h3247,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[0] } ;
  assign y__h25203 = x__h25204 & obj_mac_rg_stage2_op_2[8] ;
  assign y__h25400 = x__h25401 & obj_mac_rg_stage2_op_2[9] ;
  assign y__h25597 = x__h25598 & obj_mac_rg_stage2_op_2[10] ;
  assign y__h25794 = x__h25795 & obj_mac_rg_stage2_op_2[11] ;
  assign y__h25991 = x__h25992 & obj_mac_rg_stage2_op_2[12] ;
  assign y__h26478 =
	     { x__h26615 | y__h26616,
	       obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[1] |
	       y__h26834,
	       obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[0],
	       1'b0 } ;
  assign y__h26616 =
	     x__h26686 &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[0] ;
  assign y__h26618 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[1] ;
  assign y__h26834 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[0] ;
  assign y__h27394 =
	     { x__h27527 | y__h27528,
	       x__h28690 | y__h28691,
	       obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[0] |
	       y__h28816,
	       IF_x8335_OR_y8336_THEN_1_ELSE_0__q2[0] } ;
  assign y__h27528 = x__h27667 & IF_x8335_OR_y8336_THEN_1_ELSE_0__q2[0] ;
  assign y__h27530 =
	     x__h27600 &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[0] ;
  assign y__h27532 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[1] ;
  assign y__h2771 =
	     x__h2910 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[0] ;
  assign y__h2773 =
	     x__h2843 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[0] ;
  assign y__h2775 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[1] ;
  assign y__h28336 =
	     x__h28474 &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[0] ;
  assign y__h28338 =
	     x__h28407 &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[1] ;
  assign y__h28340 =
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_XOR_o_ETC___d594[3] &
	     obj_mac_rg_stage3_op_0_30_BITS_3_TO_0_90_AND_o_ETC___d592[2] ;
  assign y__h28691 = x__h28760 & IF_x8335_OR_y8336_THEN_1_ELSE_0__q2[0] ;
  assign y__h28693 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[0] ;
  assign y__h28816 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[0] &
	     IF_x8335_OR_y8336_THEN_1_ELSE_0__q2[0] ;
  assign y__h29256 =
	     { x__h29389 | y__h29390,
	       x__h30576 | y__h30577,
	       obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[0] |
	       y__h30702,
	       cin__h29245 } ;
  assign y__h29390 = x__h29529 & cin__h29245 ;
  assign y__h29392 =
	     x__h29462 &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[0] ;
  assign y__h29394 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[1] ;
  assign y__h30217 = x__h30447 & IF_x8335_OR_y8336_THEN_1_ELSE_0__q2[0] ;
  assign y__h30219 =
	     x__h30357 &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[0] ;
  assign y__h30221 =
	     x__h30290 &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[1] ;
  assign y__h30223 =
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_XOR_o_ETC___d573[3] &
	     obj_mac_rg_stage3_op_0_30_BITS_7_TO_4_69_AND_o_ETC___d571[2] ;
  assign y__h30577 = x__h30646 & cin__h29245 ;
  assign y__h30579 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[0] ;
  assign y__h30702 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[0] &
	     cin__h29245 ;
  assign y__h3122 =
	     x__h3191 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[0] ;
  assign y__h3124 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[1] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[0] ;
  assign y__h31279 = x__h31413 & cin__h31131 ;
  assign y__h31281 =
	     x__h31349 &
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534[0] ;
  assign y__h31283 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[2] &
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534[1] ;
  assign y__h32098 = x__h32328 & cin__h29245 ;
  assign y__h32100 =
	     x__h32238 &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[0] ;
  assign y__h32102 =
	     x__h32171 &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[1] ;
  assign y__h32104 =
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_XOR__ETC___d552[3] &
	     obj_mac_rg_stage3_op_0_30_BITS_11_TO_8_48_AND__ETC___d550[2] ;
  assign y__h32458 = x__h32524 & cin__h31131 ;
  assign y__h32460 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[1] &
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_AND_ETC___d534[0] ;
  assign y__h3247 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[0] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[0] ;
  assign y__h32578 =
	     obj_mac_rg_stage3_op_0_30_BITS_14_TO_12_31_XOR_ETC___d536[0] &
	     cin__h31131 ;
  assign y__h33322 =
	     { x__h33446 | y__h33447,
	       obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[1] |
	       y__h33665,
	       obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[0],
	       1'b0 } ;
  assign y__h33447 =
	     x__h33517 &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[0] ;
  assign y__h33449 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[2] &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[1] ;
  assign y__h33665 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[1] &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[0] ;
  assign y__h34224 =
	     { x__h34341 | y__h34342,
	       x__h35487 | y__h35488,
	       obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[0] |
	       y__h35613,
	       IF_x5132_OR_y5133_THEN_1_ELSE_0__q3[0] } ;
  assign y__h34342 = x__h34481 & IF_x5132_OR_y5133_THEN_1_ELSE_0__q3[0] ;
  assign y__h34344 =
	     x__h34414 &
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[0] ;
  assign y__h34346 =
	     p__h34220[2] &
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[1] ;
  assign y__h35133 =
	     x__h35271 &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[0] ;
  assign y__h35135 =
	     x__h35204 &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[1] ;
  assign y__h35137 =
	     obj_mac_s5_c_79_BITS_3_TO_0_24_XOR_SEXT_obj_ma_ETC___d828[3] &
	     obj_mac_s5_c_79_BITS_3_TO_0_24_AND_SEXT_obj_ma_ETC___d826[2] ;
  assign y__h35488 = x__h35557 & IF_x5132_OR_y5133_THEN_1_ELSE_0__q3[0] ;
  assign y__h35490 =
	     p__h34220[1] &
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[0] ;
  assign y__h35613 = p__h34220[0] & IF_x5132_OR_y5133_THEN_1_ELSE_0__q3[0] ;
  assign y__h36052 =
	     { x__h36169 | y__h36170,
	       x__h37339 | y__h37340,
	       obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[0] |
	       y__h37465,
	       cin__h36041 } ;
  assign y__h36170 = x__h36309 & cin__h36041 ;
  assign y__h36172 =
	     x__h36242 &
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[0] ;
  assign y__h36174 =
	     p__h36048[2] &
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[1] ;
  assign y__h36980 = x__h37210 & IF_x5132_OR_y5133_THEN_1_ELSE_0__q3[0] ;
  assign y__h36982 =
	     x__h37120 &
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[0] ;
  assign y__h36984 =
	     x__h37053 &
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[1] ;
  assign y__h36986 =
	     p__h34220[3] &
	     obj_mac_s5_c_79_BITS_7_TO_4_03_AND_SEXT_obj_ma_ETC___d805[2] ;
  assign y__h37340 = x__h37409 & cin__h36041 ;
  assign y__h37342 =
	     p__h36048[1] &
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[0] ;
  assign y__h37465 = p__h36048[0] & cin__h36041 ;
  assign y__h37904 =
	     { x__h38021 | y__h38022,
	       x__h39190 | y__h39191,
	       obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[0] |
	       y__h39316,
	       cin__h37893 } ;
  assign y__h38022 = x__h38161 & cin__h37893 ;
  assign y__h38024 =
	     x__h38094 &
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[0] ;
  assign y__h38026 =
	     p__h37900[2] &
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[1] ;
  assign y__h38831 = x__h39061 & cin__h36041 ;
  assign y__h38833 =
	     x__h38971 &
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[0] ;
  assign y__h38835 =
	     x__h38904 &
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[1] ;
  assign y__h38837 =
	     p__h36048[3] &
	     obj_mac_s5_c_79_BITS_11_TO_8_82_AND_SEXT_obj_m_ETC___d784[2] ;
  assign y__h39191 = x__h39260 & cin__h37893 ;
  assign y__h39193 =
	     p__h37900[1] &
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[0] ;
  assign y__h39316 = p__h37900[0] & cin__h37893 ;
  assign y__h39755 =
	     { x__h39872 | y__h39873,
	       x__h41041 | y__h41042,
	       obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[0] |
	       y__h41167,
	       cin__h39744 } ;
  assign y__h39873 = x__h40012 & cin__h39744 ;
  assign y__h39875 =
	     x__h39945 &
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[0] ;
  assign y__h39877 =
	     p__h39751[2] &
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[1] ;
  assign y__h40682 = x__h40912 & cin__h37893 ;
  assign y__h40684 =
	     x__h40822 &
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[0] ;
  assign y__h40686 =
	     x__h40755 &
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[1] ;
  assign y__h40688 =
	     p__h37900[3] &
	     obj_mac_s5_c_79_BITS_15_TO_12_61_AND_SEXT_obj__ETC___d763[2] ;
  assign y__h41042 = x__h41111 & cin__h39744 ;
  assign y__h41044 =
	     p__h39751[1] &
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[0] ;
  assign y__h41167 = p__h39751[0] & cin__h39744 ;
  assign y__h41606 =
	     { x__h41723 | y__h41724,
	       x__h42892 | y__h42893,
	       obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[0] |
	       y__h43018,
	       cin__h41595 } ;
  assign y__h41724 = x__h41863 & cin__h41595 ;
  assign y__h41726 =
	     x__h41796 &
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[0] ;
  assign y__h41728 =
	     p__h41602[2] &
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[1] ;
  assign y__h4229 =
	     x__h4459 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d32[0] ;
  assign y__h4231 =
	     x__h4369 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[0] ;
  assign y__h4233 =
	     x__h4302 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[1] ;
  assign y__h4235 =
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d87[3] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d85[2] ;
  assign y__h42533 = x__h42763 & cin__h39744 ;
  assign y__h42535 =
	     x__h42673 &
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[0] ;
  assign y__h42537 =
	     x__h42606 &
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[1] ;
  assign y__h42539 =
	     p__h39751[3] &
	     obj_mac_s5_c_79_BITS_19_TO_16_40_AND_SEXT_obj__ETC___d742[2] ;
  assign y__h42893 = x__h42962 & cin__h41595 ;
  assign y__h42895 =
	     p__h41602[1] &
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[0] ;
  assign y__h43018 = p__h41602[0] & cin__h41595 ;
  assign y__h43457 =
	     { x__h43574 | y__h43575,
	       x__h44743 | y__h44744,
	       obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[0] |
	       y__h44869,
	       cin__h43446 } ;
  assign y__h43575 = x__h43714 & cin__h43446 ;
  assign y__h43577 =
	     x__h43647 &
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[0] ;
  assign y__h43579 =
	     p__h43453[2] &
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[1] ;
  assign y__h44384 = x__h44614 & cin__h41595 ;
  assign y__h44386 =
	     x__h44524 &
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[0] ;
  assign y__h44388 =
	     x__h44457 &
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[1] ;
  assign y__h44390 =
	     p__h41602[3] &
	     obj_mac_s5_c_79_BITS_23_TO_20_19_AND_SEXT_obj__ETC___d721[2] ;
  assign y__h44744 = x__h44813 & cin__h43446 ;
  assign y__h44746 =
	     p__h43453[1] &
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[0] ;
  assign y__h44869 = p__h43453[0] & cin__h43446 ;
  assign y__h45307 =
	     { x__h45424 | y__h45425,
	       x__h46594 | y__h46595,
	       obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685[0] |
	       y__h46720,
	       cin__h45296 } ;
  assign y__h45425 = x__h45564 & cin__h45296 ;
  assign y__h45427 =
	     x__h45497 &
	     obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685[0] ;
  assign y__h45429 =
	     p__h45303[2] &
	     obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685[1] ;
  assign y__h46235 = x__h46465 & cin__h43446 ;
  assign y__h46237 =
	     x__h46375 &
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[0] ;
  assign y__h46239 =
	     x__h46308 &
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[1] ;
  assign y__h46241 =
	     p__h43453[3] &
	     obj_mac_s5_c_79_BITS_27_TO_24_98_AND_SEXT_obj__ETC___d700[2] ;
  assign y__h46595 = x__h46664 & cin__h45296 ;
  assign y__h46597 =
	     p__h45303[1] &
	     obj_mac_s5_c_79_BITS_31_TO_28_80_AND_SEXT_obj__ETC___d685[0] ;
  assign y__h46720 = p__h45303[0] & cin__h45296 ;
  assign y__h5203 = x__h5338 & cin__h4622 ;
  assign y__h5205 =
	     x__h5274 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[0] ;
  assign y__h5207 =
	     x__h5232 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[1] ;
  assign y__h5441 = x__h5507 & cin__h4622 ;
  assign y__h5443 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[1] &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[0] ;
  assign y__h5561 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d42[0] &
	     cin__h4622 ;
  assign y__h6636 = x__h6856 & cin__h4622 ;
  assign y__h6638 =
	     x__h6770 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[0] ;
  assign y__h6640 =
	     x__h6706 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_2__ETC___d38[1] ;
  assign y__h6642 =
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_4__ETC___d16 &
	     x__h5206 ;
  assign y__h7075 = {7{obj_mac_rg_b[7]}} ;
  assign y__h7519 =
	     { x__h7650 | y__h7651,
	       x__h7895 | y__h7896,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[0] |
	       y__h8021,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[0] } ;
  assign y__h7651 =
	     x__h7790 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[0] ;
  assign y__h7653 =
	     x__h7723 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[0] ;
  assign y__h7655 =
	     p__h7515[2] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[1] ;
  assign y__h7896 =
	     x__h7965 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[0] ;
  assign y__h7898 =
	     p__h7515[1] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[0] ;
  assign y__h8021 =
	     p__h7515[0] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[0] ;
  assign y__h9003 =
	     x__h9233 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d21[0] ;
  assign y__h9005 =
	     x__h9143 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[0] ;
  assign y__h9007 =
	     x__h9076 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[1] ;
  assign y__h9009 =
	     p__h7515[3] &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d182[2] ;
  assign y__h9406 =
	     { x__h9643 | y__h9644,
	       x__h9888 | y__h9889,
	       INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[0] |
	       y__h10014,
	       obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[5] } ;
  assign y__h9644 =
	     x__h9783 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[5] ;
  assign y__h9646 =
	     x__h9716 &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[0] ;
  assign y__h9648 =
	     p__h9402[2] &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[1] ;
  assign y__h9889 =
	     x__h9958 &
	     obj_mac_rg_a_BITS_6_TO_0_0_AND_SEXT_obj_mac_rg_ETC___d13[5] ;
  assign y__h9891 =
	     p__h9402[1] &
	     INV_obj_mac_rg_a_BIT_7_AND_obj_mac_rg_b_BIT_6__ETC___d139[0] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        as1 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	as2 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	as3 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	as4 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	as5 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	as6 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	bs1 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	bs2 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	bs3 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	bs4 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	bs5 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	bs6 <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	crg_bc <= `BSV_ASSIGNMENT_DELAY 32'd0;
	cs1 <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	cs2 <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	cs3 <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	cs4 <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	cs5 <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	cs6 <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	fail <= `BSV_ASSIGNMENT_DELAY 11'd0;
	obj_mac_rg_a <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_rg_b <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_rg_stage1_op_0 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage1_op_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage1_op_2 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage1_op_3 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage1_op_4 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage2_op_0 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage2_op_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage2_op_2 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage3_op_0 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage3_op_1 <= `BSV_ASSIGNMENT_DELAY 16'd0;
	obj_mac_rg_stage4_op <= `BSV_ASSIGNMENT_DELAY 16'hAAAA;
	obj_mac_rg_stage5_op <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	obj_mac_s1_a <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s1_b <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s1_c <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	obj_mac_s2_a <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s2_b <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s2_c <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	obj_mac_s3_a <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s3_b <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s3_c <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	obj_mac_s4_a <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s4_b <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s4_c <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	obj_mac_s5_a <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s5_b <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	obj_mac_s5_c <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	rg_A <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	rg_B <= `BSV_ASSIGNMENT_DELAY 8'hAA;
	rg_C <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	rg_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	s1_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	s2_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	s3_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	s4_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	s5_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
	s6_MAC <= `BSV_ASSIGNMENT_DELAY 32'hAAAAAAAA;
      end
    else
      begin
        if (as1$EN) as1 <= `BSV_ASSIGNMENT_DELAY as1$D_IN;
	if (as2$EN) as2 <= `BSV_ASSIGNMENT_DELAY as2$D_IN;
	if (as3$EN) as3 <= `BSV_ASSIGNMENT_DELAY as3$D_IN;
	if (as4$EN) as4 <= `BSV_ASSIGNMENT_DELAY as4$D_IN;
	if (as5$EN) as5 <= `BSV_ASSIGNMENT_DELAY as5$D_IN;
	if (as6$EN) as6 <= `BSV_ASSIGNMENT_DELAY as6$D_IN;
	if (bs1$EN) bs1 <= `BSV_ASSIGNMENT_DELAY bs1$D_IN;
	if (bs2$EN) bs2 <= `BSV_ASSIGNMENT_DELAY bs2$D_IN;
	if (bs3$EN) bs3 <= `BSV_ASSIGNMENT_DELAY bs3$D_IN;
	if (bs4$EN) bs4 <= `BSV_ASSIGNMENT_DELAY bs4$D_IN;
	if (bs5$EN) bs5 <= `BSV_ASSIGNMENT_DELAY bs5$D_IN;
	if (bs6$EN) bs6 <= `BSV_ASSIGNMENT_DELAY bs6$D_IN;
	if (crg_bc$EN) crg_bc <= `BSV_ASSIGNMENT_DELAY crg_bc$D_IN;
	if (cs1$EN) cs1 <= `BSV_ASSIGNMENT_DELAY cs1$D_IN;
	if (cs2$EN) cs2 <= `BSV_ASSIGNMENT_DELAY cs2$D_IN;
	if (cs3$EN) cs3 <= `BSV_ASSIGNMENT_DELAY cs3$D_IN;
	if (cs4$EN) cs4 <= `BSV_ASSIGNMENT_DELAY cs4$D_IN;
	if (cs5$EN) cs5 <= `BSV_ASSIGNMENT_DELAY cs5$D_IN;
	if (cs6$EN) cs6 <= `BSV_ASSIGNMENT_DELAY cs6$D_IN;
	if (fail$EN) fail <= `BSV_ASSIGNMENT_DELAY fail$D_IN;
	if (obj_mac_rg_a$EN)
	  obj_mac_rg_a <= `BSV_ASSIGNMENT_DELAY obj_mac_rg_a$D_IN;
	if (obj_mac_rg_b$EN)
	  obj_mac_rg_b <= `BSV_ASSIGNMENT_DELAY obj_mac_rg_b$D_IN;
	if (obj_mac_rg_stage1_op_0$EN)
	  obj_mac_rg_stage1_op_0 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage1_op_0$D_IN;
	if (obj_mac_rg_stage1_op_1$EN)
	  obj_mac_rg_stage1_op_1 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage1_op_1$D_IN;
	if (obj_mac_rg_stage1_op_2$EN)
	  obj_mac_rg_stage1_op_2 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage1_op_2$D_IN;
	if (obj_mac_rg_stage1_op_3$EN)
	  obj_mac_rg_stage1_op_3 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage1_op_3$D_IN;
	if (obj_mac_rg_stage1_op_4$EN)
	  obj_mac_rg_stage1_op_4 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage1_op_4$D_IN;
	if (obj_mac_rg_stage2_op_0$EN)
	  obj_mac_rg_stage2_op_0 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage2_op_0$D_IN;
	if (obj_mac_rg_stage2_op_1$EN)
	  obj_mac_rg_stage2_op_1 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage2_op_1$D_IN;
	if (obj_mac_rg_stage2_op_2$EN)
	  obj_mac_rg_stage2_op_2 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage2_op_2$D_IN;
	if (obj_mac_rg_stage3_op_0$EN)
	  obj_mac_rg_stage3_op_0 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage3_op_0$D_IN;
	if (obj_mac_rg_stage3_op_1$EN)
	  obj_mac_rg_stage3_op_1 <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage3_op_1$D_IN;
	if (obj_mac_rg_stage4_op$EN)
	  obj_mac_rg_stage4_op <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage4_op$D_IN;
	if (obj_mac_rg_stage5_op$EN)
	  obj_mac_rg_stage5_op <= `BSV_ASSIGNMENT_DELAY
	      obj_mac_rg_stage5_op$D_IN;
	if (obj_mac_s1_a$EN)
	  obj_mac_s1_a <= `BSV_ASSIGNMENT_DELAY obj_mac_s1_a$D_IN;
	if (obj_mac_s1_b$EN)
	  obj_mac_s1_b <= `BSV_ASSIGNMENT_DELAY obj_mac_s1_b$D_IN;
	if (obj_mac_s1_c$EN)
	  obj_mac_s1_c <= `BSV_ASSIGNMENT_DELAY obj_mac_s1_c$D_IN;
	if (obj_mac_s2_a$EN)
	  obj_mac_s2_a <= `BSV_ASSIGNMENT_DELAY obj_mac_s2_a$D_IN;
	if (obj_mac_s2_b$EN)
	  obj_mac_s2_b <= `BSV_ASSIGNMENT_DELAY obj_mac_s2_b$D_IN;
	if (obj_mac_s2_c$EN)
	  obj_mac_s2_c <= `BSV_ASSIGNMENT_DELAY obj_mac_s2_c$D_IN;
	if (obj_mac_s3_a$EN)
	  obj_mac_s3_a <= `BSV_ASSIGNMENT_DELAY obj_mac_s3_a$D_IN;
	if (obj_mac_s3_b$EN)
	  obj_mac_s3_b <= `BSV_ASSIGNMENT_DELAY obj_mac_s3_b$D_IN;
	if (obj_mac_s3_c$EN)
	  obj_mac_s3_c <= `BSV_ASSIGNMENT_DELAY obj_mac_s3_c$D_IN;
	if (obj_mac_s4_a$EN)
	  obj_mac_s4_a <= `BSV_ASSIGNMENT_DELAY obj_mac_s4_a$D_IN;
	if (obj_mac_s4_b$EN)
	  obj_mac_s4_b <= `BSV_ASSIGNMENT_DELAY obj_mac_s4_b$D_IN;
	if (obj_mac_s4_c$EN)
	  obj_mac_s4_c <= `BSV_ASSIGNMENT_DELAY obj_mac_s4_c$D_IN;
	if (obj_mac_s5_a$EN)
	  obj_mac_s5_a <= `BSV_ASSIGNMENT_DELAY obj_mac_s5_a$D_IN;
	if (obj_mac_s5_b$EN)
	  obj_mac_s5_b <= `BSV_ASSIGNMENT_DELAY obj_mac_s5_b$D_IN;
	if (obj_mac_s5_c$EN)
	  obj_mac_s5_c <= `BSV_ASSIGNMENT_DELAY obj_mac_s5_c$D_IN;
	if (rg_A$EN) rg_A <= `BSV_ASSIGNMENT_DELAY rg_A$D_IN;
	if (rg_B$EN) rg_B <= `BSV_ASSIGNMENT_DELAY rg_B$D_IN;
	if (rg_C$EN) rg_C <= `BSV_ASSIGNMENT_DELAY rg_C$D_IN;
	if (rg_MAC$EN) rg_MAC <= `BSV_ASSIGNMENT_DELAY rg_MAC$D_IN;
	if (s1_MAC$EN) s1_MAC <= `BSV_ASSIGNMENT_DELAY s1_MAC$D_IN;
	if (s2_MAC$EN) s2_MAC <= `BSV_ASSIGNMENT_DELAY s2_MAC$D_IN;
	if (s3_MAC$EN) s3_MAC <= `BSV_ASSIGNMENT_DELAY s3_MAC$D_IN;
	if (s4_MAC$EN) s4_MAC <= `BSV_ASSIGNMENT_DELAY s4_MAC$D_IN;
	if (s5_MAC$EN) s5_MAC <= `BSV_ASSIGNMENT_DELAY s5_MAC$D_IN;
	if (s6_MAC$EN) s6_MAC <= `BSV_ASSIGNMENT_DELAY s6_MAC$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    as1 = 8'hAA;
    as2 = 8'hAA;
    as3 = 8'hAA;
    as4 = 8'hAA;
    as5 = 8'hAA;
    as6 = 8'hAA;
    bs1 = 8'hAA;
    bs2 = 8'hAA;
    bs3 = 8'hAA;
    bs4 = 8'hAA;
    bs5 = 8'hAA;
    bs6 = 8'hAA;
    crg_bc = 32'hAAAAAAAA;
    cs1 = 32'hAAAAAAAA;
    cs2 = 32'hAAAAAAAA;
    cs3 = 32'hAAAAAAAA;
    cs4 = 32'hAAAAAAAA;
    cs5 = 32'hAAAAAAAA;
    cs6 = 32'hAAAAAAAA;
    fail = 11'h2AA;
    obj_mac_rg_a = 8'hAA;
    obj_mac_rg_b = 8'hAA;
    obj_mac_rg_stage1_op_0 = 16'hAAAA;
    obj_mac_rg_stage1_op_1 = 16'hAAAA;
    obj_mac_rg_stage1_op_2 = 16'hAAAA;
    obj_mac_rg_stage1_op_3 = 16'hAAAA;
    obj_mac_rg_stage1_op_4 = 16'hAAAA;
    obj_mac_rg_stage2_op_0 = 16'hAAAA;
    obj_mac_rg_stage2_op_1 = 16'hAAAA;
    obj_mac_rg_stage2_op_2 = 16'hAAAA;
    obj_mac_rg_stage3_op_0 = 16'hAAAA;
    obj_mac_rg_stage3_op_1 = 16'hAAAA;
    obj_mac_rg_stage4_op = 16'hAAAA;
    obj_mac_rg_stage5_op = 32'hAAAAAAAA;
    obj_mac_s1_a = 8'hAA;
    obj_mac_s1_b = 8'hAA;
    obj_mac_s1_c = 32'hAAAAAAAA;
    obj_mac_s2_a = 8'hAA;
    obj_mac_s2_b = 8'hAA;
    obj_mac_s2_c = 32'hAAAAAAAA;
    obj_mac_s3_a = 8'hAA;
    obj_mac_s3_b = 8'hAA;
    obj_mac_s3_c = 32'hAAAAAAAA;
    obj_mac_s4_a = 8'hAA;
    obj_mac_s4_b = 8'hAA;
    obj_mac_s4_c = 32'hAAAAAAAA;
    obj_mac_s5_a = 8'hAA;
    obj_mac_s5_b = 8'hAA;
    obj_mac_s5_c = 32'hAAAAAAAA;
    rg_A = 8'hAA;
    rg_B = 8'hAA;
    rg_C = 32'hAAAAAAAA;
    rg_MAC = 32'hAAAAAAAA;
    s1_MAC = 32'hAAAAAAAA;
    s2_MAC = 32'hAAAAAAAA;
    s3_MAC = 32'hAAAAAAAA;
    s4_MAC = 32'hAAAAAAAA;
    s5_MAC = 32'hAAAAAAAA;
    s6_MAC = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (crg_bc == 32'd1048)
	$display("PASS: %d  FAIL: %d", 11'd1048 - fail, fail);
    if (RST_N != `BSV_RESET_VALUE) if (crg_bc == 32'd1048) $finish(32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_comp && obj_mac_rg_stage5_op_023_EQ_s6_MAC_024___d1025)
	$display("%d * %d + %d = %d  expected: %d",
		 as6,
		 bs6,
		 cs6,
		 obj_mac_rg_stage5_op,
		 s6_MAC);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_comp &&
	  !obj_mac_rg_stage5_op_023_EQ_s6_MAC_024___d1025)
	$display("%d * %d + %d = %d  expected: %d",
		 as6,
		 bs6,
		 cs6,
		 obj_mac_rg_stage5_op,
		 s6_MAC);
  end
  // synopsys translate_on
endmodule  // mkTb

